name: Terraform apply 

on:
    workflow_dispatch:

env:
    AWS_REGION: us-east-1

jobs:
    terraform:
        runs-on: ubuntu-latest

    
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}

            - name: Download tfvars file from S3
              run: aws s3 cp s3://my-terraform-config-bucket-david/terraform.tfvars terraform/terraform.tfvars

            - name: Setup Terraform 
              uses: hashicorp/setup-terraform@v3

            - name: Download Terraform Plan Artifact
              uses: actions/download-artifact@v4
              with:
                name: tfplan
                path: terraform

            - name: Terraform init
              run: terraform init 
              working-directory: terraform

            - name: Terraform Apply
              run: terraform apply -auto-approve terraform/tfplan
              working-directory: terraform 

            - name: Summary
              run: echo "### Terraform Aplly Completed" >> $GITHUB_STEP_SUMMARY